
/* Drop Tables */

DROP TABLE board01 CASCADE CONSTRAINTS;
DROP TABLE member01 CASCADE CONSTRAINTS;
DROP TABLE SYSTEM.BOARD1209 CASCADE CONSTRAINTS;
DROP TABLE SYSTEM.MEMBER1209 CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE board01
(
	bId number NOT NULL,
	bTitle varchar2(100) NOT NULL,
	bContent varchar2(255) NOT NULL,
	bwriteId varchar2(10) NOT NULL,
	userId varchar2(10) NOT NULL,
	PRIMARY KEY (bId)
);


CREATE TABLE member01
(
	userId varchar2(10) NOT NULL,
	userPw varchar2(10) NOT NULL,
	email varchar2(200) NOT NULL,
	PRIMARY KEY (userId)
);


CREATE TABLE SYSTEM.BOARD1209
(
	BID  NOT NULL,
	TITLE varchar2(10 char) NOT NULL,
	CONTENT varchar2(100 char) NOT NULL,
	MID  NOT NULL,
	CONSTRAINT SYS_C007135 PRIMARY KEY (BID)
);


CREATE TABLE SYSTEM.MEMBER1209
(
	MID  NOT NULL,
	USERID varchar2(10 char) NOT NULL,
	USERPW varchar2(10 char) NOT NULL,
	EMAIL varchar2(10 char) NOT NULL,
	CONSTRAINT SYS_C007130 PRIMARY KEY (MID)
);



/* Create Foreign Keys */

ALTER TABLE board01
	ADD FOREIGN KEY (userId)
	REFERENCES member01 (userId)
;


ALTER TABLE SYSTEM.BOARD1209
	ADD CONSTRAINT FK_MID FOREIGN KEY (MID)
	REFERENCES SYSTEM.MEMBER1209 (MID)
;



